# Generated by Django 4.2.5 on 2023-12-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_product_karsi_takas_product_urun_aciklamasi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
